apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    role: hln-rules
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
  name: {{ include "<CHARTNAME>.fullname" . }}
spec:
  groups:
  - name: h8r.io/rules
    rules:
    - alert: remixSerivceAlert
      expr: "remix_error_500_count_total > 0"
